---
  fav:
    color: yellow
    fruit: gauva
    
  dbconn:
    host: db
    user: devops
    pass: devops
    db: devopsdemo
    
  haproxy_backend_servers:
    - name: app1
      address: 192.168.61.12:80
    - name: app2
      address: 192.168.61.13:80
  haproxy_backend_httpchk: ''
  haproxy_socket: /var/run/haproxy.sock
  
  mysql_root_password: devops
  mysql_databases:
    - name: devopsdemo
      encoding: latin1
      collation: latin1_general_ci
  mysql_users:
    - name: devops
      host: "%"
      password: devops
      priv: "devopsdemo.*:ALL"
  mysql_bind_address: '0.0.0.0'